### ISSUE TITLE
update Necrobot to version 0.90

### ISSUE THREAD

**Issue by iamspa** [vandernorth/NecroBot.GUI#67] opened 2016-08-16 03:31 UTC
sir...
can you update the necro bot to lastest version?
https://github.com/NoxxDev/NecroBot/releases/
because it fix lot than previous release....

**Comment by RuneMykle** [comment] 2016-08-16 12:48
Runtime 2 hours on this one now with no problems at my end.

**Comment by vandernorth** [comment] 2016-08-16 21:11
Duplicate of #27

**Closed by vandernorth** 2016-08-16 21:11 UTC
Labels: duplicate

**Comment by iamspa** [comment] 2016-08-18 10:14
sry for duplicate, because just download and read Issue....
thank for such nice tools....
