### ISSUE TITLE
Reuest (autologin - autologoff)

### ISSUE THREAD

**Issue by mirdhan123** [vandernorth/NecroBot.GUI#46] opened 2016-08-15 04:08 UTC
can you add auto login/logoff based on the number pokestop we have spinned?
ex: the bot will logoff after we have spin 200 pokestop

**Comment by vandernorth** [comment] 2016-08-15 19:39
Do you want the bot to stop completely after 200 pokestops, restart directly or restart with delay?

**Comment by RogueMaster** [comment] 2016-08-16 07:34
Can you make it restart immediately with a secondary account?

**Comment by vandernorth** [comment] 2016-08-16 21:41
Sort of duplicate of #63 Lets continue there.

**Closed by vandernorth** 2016-08-16 21:41 UTC
