### ISSUE TITLE
able to schedule run time ?

### ISSUE THREAD

**Issue by hefenglim** [vandernorth/NecroBot.GUI#111] opened 2016-08-19 05:12 UTC
able to set a schedule run time ex bot run 2 hours & showdown program.

**Comment by czokalapik** [comment] 2016-08-19 12:57
launch bot and use http://www.airytec.com/en/switch-off/ to shedule PC shutdown

**Comment by vandernorth** [comment] 2016-08-20 09:11
duplicate of #63

**Closed by vandernorth** 2016-08-20 09:11 UTC
