### ISSUE TITLE
Feature Request -  DailyMaxPokemon/Stops Killswitch!

### ISSUE THREAD

**Issue by f3l1p1nh07** [vandernorth/NecroBot.GUI#65] opened 2016-08-16 02:32 UTC
http://i.imgur.com/2ghAYvo.png

Add this function please

Killswitch - Going to be away from your computer? Set a killswitch value to have the bot close once a certain number of Pokemon are caught or Pokestops are looted.

**Comment by vandernorth** [comment] 2016-08-16 21:27
Duplicate of #61

**Closed by vandernorth** 2016-08-16 21:27 UTC
Labels: duplicate
