### ISSUE TITLE
Necronbot 8.8 att for new 9.0

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#62] opened 2016-08-15 22:21 UTC
your use Necro 9.0 ofical em new release.
http://www.mpgh.net/forum/showthread.php?t=1154457

**Comment by f3l1p1nh07** [comment] 2016-08-16 02:32
http://i.imgur.com/2ghAYvo.png

Add this function please 

Killswitch - Going to be away from your computer? Set a killswitch value to have the bot close once a certain number of Pokemon are caught or Pokestops are looted.

**Comment by vandernorth** [comment] 2016-08-16 21:11
Duplicate of #27

**Closed by vandernorth** 2016-08-16 21:11 UTC
Labels: duplicate
