### ISSUE TITLE
[Feature request] Noxx/dev NecroBot v0.9.6

### ISSUE THREAD

**Issue by latte222** [vandernorth/NecroBot.GUI#151] opened 2016-08-25 23:13 UTC
Feature request
https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.6

Fix
[FeroxRev Critical NoxxDev/NecroBot-Rocket-API@2e2ee2a]
[Humal walk snipe fix config reset 7365d99]
[Humal walk snipe bug fix/enhancement 53393f0]
Update

[extra information about snipping options #499 d775d8a]
Add

[Added /help /exit Telegram command f233ef2]

**Comment by vandernorth** [comment] 2016-08-28 14:42
Dupe of #147. Please check other issues first next time..

**Closed by vandernorth** 2016-08-28 14:42 UTC
Labels: duplicate
