### ISSUE TITLE
Pogo Location Feeder

### ISSUE THREAD

**Issue by xratedownz** [vandernorth/NecroBot.GUI#9] opened 2016-08-11 18:13 UTC
I am using pogo location feeder for sniping (its very popular)
But its not working with your gui. Can you fix this please? Ty.

**Comment by vandernorth** [comment] 2016-08-11 18:14
Duplicate of #4

**Closed by vandernorth** 2016-08-11 18:14 UTC
Labels: duplicate

**Comment by vandernorth** [comment] 2016-08-11 20:36
Fixed in https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.2
