### ISSUE TITLE
Request Update for Necro 8.8 ?

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#47] opened 2016-08-15 04:34 UTC
you plan to upgrade the necrobot the release of 0.8.6 to 8.8?

now continued by a User who took the official step desnvolvedora he officially continue the project
Link:
http://www.mpgh.net/forum/showthread.php?t=1154457

**Comment by hklcf** [comment] 2016-08-15 06:59
lastest Necro here
https://github.com/NECROBOTIO/NecroBot/tree/e4686900abe46d90284c62bc693fd37d067e0584

**Comment by LiraGamer** [comment] 2016-08-15 15:03
New dev official!

**Comment by vandernorth** [comment] 2016-08-15 15:25
DUPLICATE of #27

**Closed by vandernorth** 2016-08-15 15:25 UTC
Labels: duplicate
